### ISSUE TITLE
Fix for: FileNotFoundError: No such file or directory or  [kitti_rec]: Error: Odom directory not found:

### ISSUE THREAD

**Issue by Basavaraj-PN** [bharadwajsirigadi/kitti_odom-ros2_bag#3]
# FIX 🚀

Change line 11 and  12 in https://github.com/bharadwajsirigadi/kitti2rosbag2/blob/d38b27cc84c64329f778570d081d2752b0779d05/kitti2rosbag2/utils/kitti_utils.py#L11

```python 
LEFT_IMG_FOLDER = "image_0"
RIGHT_IMG_FOLDER = "image_1"
```

Correct example `params.yaml`:
```yaml
kitti_rec:
  ros__parameters:
    sequence: 0
    data_dir: '/home/user_name/Download/data_odometry_gray/dataset/'
    odom_dir: '/home/user_name/Download/data_odometry_poses/dataset/'
    bag_dir : '/home/user_name/Download/00_bag'
    odom : True
```

`data_odometry_poses` can be found here.:

[data_odometry_poses.zip](https://github.com/bharadwajsirigadi/kitti2rosbag2/files/14692772/data_odometry_poses.zip)
